# Generated by Django 2.2.5 on 2019-09-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseware',
            name='courseware_time',
            field=models.TimeField(),
        ),
    ]
