# Generated by Django 2.2.5 on 2019-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='asc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
