# Generated by Django 2.2.5 on 2019-09-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_course', '0002_uservideo_asc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideo',
            name='asc',
        ),
    ]
