# Generated by Django 2.2.5 on 2019-09-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190923_1813'),
        ('user', '0002_auto_20190920_2227'),
        ('user_course', '0004_auto_20190923_2011'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercourseware',
            unique_together={('courseware', 'user')},
        ),
    ]
