# Generated by Django 2.2.5 on 2019-09-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190920_2227'),
        ('course', '0002_auto_20190923_1813'),
        ('user_course', '0005_auto_20190923_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='selectcourse',
            unique_together={('user', 'course')},
        ),
    ]
